export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const AUTH_LOADING = "AUTH_LOADING";

//users
export const USER_LOADING = "USER_LOADING";
export const USERS_LOADING = "USERS_LOADING";
export const USER_SAVED = "USER_SAVED";
export const GET_USER = "GET_USER";
export const GET_USERS = "GET_USERS";
export const USERS_ERROR = "USERS_ERROR";
export const USER_ERROR = "USER_ERROR";
export const USER_DELETED = "USER_DELETED";
export const USER_UPDATED = "USER_UPDATED";
export const PASSWORD_UPDATED = "PASSWORD_UPDATED";
export const PASSWORD_ERROR = "PASSWORD_ERROR";
export const CODE_VERIFIED = "CODE_VERIFIED";
export const VERIFCATION_ERROR = "VERIFCATION_ERROR";
export const PASSWORD_CONFIRMATION = "PASSWORD_CONFIRMATION";
export const GET_ASSIGNED_ARTICLES = "GET_ASSIGNED_ARTICLES";

//change page
export const CHANGE_PAGE = "CHANGE_PAGE";

//alerts
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

// dashboard
export const SHOP_STARTED = "SHOP_STARTED";
export const SHOP_STOPPED = "SHOP_STOPPED";
export const DASHBOARD_LOADING = "DASHBOARD_LOADING";
export const DASHBOARD_LOADED = "DASHBOARD_LOADED";
export const DASHBOARD_ERROR = "DASHBOARD_ERROR";
export const SHOP_LOADING = "SHOP_LOADING";
export const SHOP_LOADED = "SHOP_LOADED";
export const SHOP_ERROR = "SHOP_ERROR";

// articles
export const ARTICLE_LOADING = "ARTICLE_LOADING";
export const ARTICLES_LOADING = "ARTICLES_LOADING";
export const ARTICLE_SAVED = "ARTICLE_SAVED";
export const GET_ARTICLE = "GET_ARTICLE";
export const GET_ARTICLES = "GET_ARTICLES";
export const GET_ARTICLES_BY_PAGE_NO = "GET_ARTICLES_BY_PAGE_NO";
export const ARTICLES_ERROR = "ARTICLES_ERROR";
export const ARTICLE_ERROR = "ARTICLE_ERROR";
export const DELETE_ARTICLE = "DELETE_ARTICLE";

// emailConfig
export const EMAIL_CONFIG_LOADING = "EMAIL_CONFIG_LOADING";
export const EMAIL_CONFIG_SAVING = "EMAIL_CONFIG_SAVING";
export const GET_EMAIL_CONFIG = "GET_EMAIL_CONFIG";
export const EMAIL_CONFIG_SAVED = "EMAIL_CONFIG_SAVED";
export const EMAIL_CONFIG_ERROR = "EMAIL_CONFIG_ERROR";

//words
export const WORDS_LOADING = "WORDS_LOADING";
export const GET_WORDS = "GET_WORDS";
export const GET_WORD = "GET_WORD";
export const GET_UNSUBMITTED_WORDS_COUNT = "GET_UNSUBMITTED_WORDS_COUNT";
export const WORDS_ERROR = "WORDS_ERROR";
export const WORD_SAVING = "WORD_SAVING";
export const WORD_SAVED = "WORD_SAVED";
export const GET_FOUND_WORDS = "GET_FOUND_WORDS";
export const DELETE_WORD = "DELETE_WORD";

//Report Bug
export const BUG_SAVING = "BUG_SAVING";
export const GET_BUGS = "GET_BUGS";
export const DELETE_BUG = "DELETE_BUG";
export const REPORT_BUG_ERROR = "REPORT_BUG_ERROR";
export const REPORT_BUG_LOADING = "REPORT_BUG_LOADING";
export const BUG_SAVED = "BUG_SAVED";
export const REPORT_BUG_POPUP_STATUS = "REPORT_BUG_POPUP_STATUS";
export const REPORT_BUG_IMG_SRC = "REPORT_BUG_IMG_SRC";
